apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.9.5
        ports:
        - containerPort: 5672
        - containerPort: 15672
